### ISSUE TITLE
Stop-HetznerCloudServer - what ID?

### ISSUE THREAD

**Issue by davedaved** [nicholasdille/PowerShell-HetznerCloud#25]
Hello.
I want to stop a vserver in my hetzner project.
Stop-HetznerCloudServer asks for an ID?

What ID is that? In Hetzner Cloud Console I only see the name of the server, but no ID.
Thanks.

**Comment by nicholasdille** [comment]
Hi, every server has a unique ID. By default, `Get-HetznerCloudServer` hides the ID but you can display all properties as described in the cmdlet help. There is an online copy here: https://github.com/nicholasdille/PowerShell-HetznerCloud/blob/master/Docs/en-US/Get-HetznerCloudServer.md#example-3

**Comment by davedaved** [comment]
Hi. Thank you very much. That helped.
